# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farhoodapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='type',
            new_name='event_type',
        ),
    ]
