# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farhoodapp', '0004_auto_20171211_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='farhoodapp.User'),
            preserve_default=False,
        ),
    ]
