# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-03 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import farhoodapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('farhoodapp', '0007_auto_20171213_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=farhoodapp.models.upload_profile_image),
        ),
    ]
