# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-03 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import farhoodapp.models
import farhoodapp.utils.overwritestorage


class Migration(migrations.Migration):

    dependencies = [
        ('farhoodapp', '0009_auto_20180104_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=farhoodapp.utils.overwritestorage.OverwriteStorage(), upload_to=farhoodapp.models.upload_profile_image),
        ),
    ]
