# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-04 00:07
from __future__ import unicode_literals

from django.db import migrations, models
import farhoodapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('farhoodapp', '0010_auto_20180104_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=farhoodapp.models.upload_profile_image),
        ),
    ]
