# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-09 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farhoodapp', '0011_auto_20180104_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('coffee', 'Coffee'), ('beer', 'Beer'), ('shopping', 'Shopping'), ('dinning', 'Dinning'), ('logo', 'Logo'), ('sports', 'Sports')], default='coffee', max_length=150),
        ),
    ]
