# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-08 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farhoodapp', '0012_auto_20180109_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
