# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-26 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farhoodapp', '0013_auto_20180208_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default=b'', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default=b'', max_length=150, null=True),
        ),
    ]
