# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-27 14:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farhoodapp', '0016_auto_20180327_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventWishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farhoodapp.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='eventwishlist',
            unique_together=set([('user', 'event')]),
        ),
    ]
